// AUTO-GENERATED by @colorfont/core. DO NOT EDIT.

export type IconName =
  | "arrow-left"
  | "badge-grad"
  | "home"
  | "logo-color"
  | "star";

export const codepoints = {
  "arrow-left": 0xe000,
  "badge-grad": 0xe001,
  "home": 0xe002,
  "logo-color": 0xe003,
  "star": 0xe004,
} as const satisfies Record<IconName, number>;

/** 图标名 → CSS 类名。 */
export const icons = {
  "arrow-left": "icon-arrow-left",
  "badge-grad": "icon-badge-grad",
  "home": "icon-home",
  "logo-color": "icon-logo-color",
  "star": "icon-star",
} as const satisfies Record<IconName, string>;

/** 挂字体的基础类名(不含点)。 */
export const baseName = "icon";

/** 多色图标(在支持 COLR/OT-SVG 的浏览器彩色渲染)。对象形式便于 O(1) 判定:colorIcons[name]。 */
export const colorIcons = {
  "badge-grad": true,
  "logo-color": true,
} as const satisfies Partial<Record<IconName, true>>;

export function iconContent(name: IconName): string {
  return String.fromCodePoint(codepoints[name]);
}
