import type { FontMetadata, ResolvedOptions } from '../types.ts'

/** 生成类型安全的自产 TS 入口(IconName 联合 + codepoints + icons 类名映射 + colorIcons)。 */
export function emitDts(metadata: FontMetadata, o: ResolvedOptions): string {
  const glyphs = metadata.glyphs
  const q = (s: string) => JSON.stringify(s)
  const hex = (n: number) => '0x' + n.toString(16)

  const union = glyphs.length
    ? glyphs.map((g) => `  | ${q(g.name)}`).join('\n')
    : '  | never'

  const cp = glyphs.map((g) => `  ${q(g.name)}: ${hex(g.codepoint)},`).join('\n')
  const cls = glyphs.map((g) => `  ${q(g.name)}: ${q(o.classPrefix + g.name)},`).join('\n')
  // 对象形式:便于外部 O(1) 判定 colorIcons[name] 是否彩色(只列出彩色图标)
  const colorObj = glyphs
    .filter((g) => g.color)
    .map((g) => `  ${q(g.name)}: true,`)
    .join('\n')

  return `// AUTO-GENERATED by @colorfont/core. DO NOT EDIT.

export type IconName =
${union};

export const codepoints = {
${cp}
} as const satisfies Record<IconName, number>;

/** 图标名 → CSS 类名。 */
export const icons = {
${cls}
} as const satisfies Record<IconName, string>;

/** 挂字体的基础类名(不含点)。 */
export const baseName = ${q(o.baseSelector.replace(/^\./, ''))};

/** 多色图标(在支持 COLR/OT-SVG 的浏览器彩色渲染)。对象形式便于 O(1) 判定:colorIcons[name]。 */
export const colorIcons = {
${colorObj}
} as const satisfies Partial<Record<IconName, true>>;

export function iconContent(name: IconName): string {
  return String.fromCodePoint(codepoints[name]);
}
`
}
